name: formul_mat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: gerÃ§ek
  image_path: "assets/resimler/project_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/resimler/resim5.jpeg
    - assets/resimler/bes_1.png
    - assets/resimler/bes_2.png
    - assets/resimler/alti_1.png
    - assets/resimler/alti_2.png
    - assets/resimler/yedi_1.png
    - assets/resimler/yedi_2.png
    - assets/resimler/sekiz_1.png
    - assets/resimler/sekiz_2.png
    - assets/resimler/dokuz_1.png
    - assets/resimler/dokuz_2.png
    - assets/resimler/on_1.png
    - assets/resimler/on_2.png
    - assets/resimler/onbir_1.png
    - assets/resimler/onbir_2.png
    - assets/resimler/oniki_1.png
    - assets/resimler/oniki_2.png
    - assets/resimler/uni_1.png
    - assets/resimler/uni_2.png




  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

Fonts:
     - family: Noto_Sans_Math
       fonts:
         -asset: Noto_Sans_Math-Regular.ttf

     - family: Schyler
       fonts:
         - asset: fonts/Schyler-Regular.ttf
         - asset: fonts/Schyler-Italic.ttf
           style: italic
     - family: Trajan Pro
       fonts:
         - asset: fonts/TrajanPro.ttf
         - asset: fonts/TrajanPro_Bold.ttf
           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
